version: 2

updates:
  - directory: /
    open-pull-requests-limit: 10
    package-ecosystem: bundler
    target-branch: main
    schedule:
      interval: weekly
    labels:
      - dependencies
    assignees:
      - clarkedb
