name: CI

on: push

env:
  GIT_COMMIT_SHA: ${{ github.sha }}
  GIT_BRANCH: ${{ github.ref }}

jobs:
  test-unit:
    runs-on: ubuntu-latest
    name: unit tests (ruby v${{ matrix.ruby }})
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6', '2.7', '3.0' ]

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Test
        continue-on-error: ${{ matrix.experimental }}
        run: bundle exec rake test
