name: CI

on: push

env:
  CI: true
  GIT_COMMIT_SHA: ${{ github.sha }}
  GIT_BRANCH: ${{ github.ref }}

jobs:
  linting:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITH: lint
      BUNDLE_WITHOUT: development:test

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby 3.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Rubocop
        run: bundle exec rubocop --format progress

  build:
    needs: [linting]
    runs-on: ubuntu-latest
    name: build (ruby v${{ matrix.ruby }})
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7", "3.0", "3.1", "3.2", "3.3"]

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Test
        run: bundle exec rake test

      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/.resultset.json
          name: codecov-umbrella
          verbose: true
          fail_ci_if_error: true
